### PR TITLE
Clean up the main() function

### PR DESCRIPTION
**Pull request by bgruening**
It seems that the current setup.py setup needs to have a clean main() function.
Anyone know what is the preferred Python way to handle such a setup? I have seen many projects that writes the `bin/*` on there own.

### CODE REVIEW

**Comment by jmchilton** [comment]
@bgruening For what it is worth - I prefer this version to previous. I'm +1 on this as is but if you want to spend more time coming up with a best practice Python standard let me know.

**Comment by bgruening** [comment]
@jmchilton I'm fine with this. It was a little bit unexpected to have a main() function without parameter, I was just wondering if this is the best-practice or if there is anything else.
Please feel free to merge and release a new version :)

**Comment by bgruening** [comment]
Thanks!!!

**Comment by jmchilton** [comment]
https://pypi.python.org/pypi/ephemeris

**Pull request merged**
